### PR TITLE
fix integer overflow when ctts contains entries with negative offsets

### PR DESCRIPTION
**Pull request by Wumpf**
Fixes a debug crash with this video. 
See
* https://github.com/rerun-io/rerun/issues/8093

### CODE REVIEW

**Review by emilk — APPROVED** [review]
Does the video have a freeze-frame at the ends with an infinite duration or something? O.o

**Comment by Wumpf** [comment]
`sample_offset` is an i32 to begin with

**Comment by Wumpf** [comment]
ah yeah it can definitely be negative. So our cast there to i64 was wrong
https://developer.apple.com/documentation/quicktime-file-format/composition_offset_atom

that's for MOV, but surely holds up for MP4 as well I'd guess

**Comment by Wumpf** [comment]
👍 I'll have a quick pass, but I don't want to divulge into more spec reading right now....

**Pull request merged**
